### PR TITLE
Add support for Packer

### PR DESCRIPTION
**Pull request by gegoune**
Added couple of colours for Packer which should make it easier to read change logs.

Before:
before
After:
after

### CODE REVIEW

**Review by andersevenrud — CHANGES_REQUESTED** [review]
Nice! This will make it easier to read indeed :)

~~Just a nitpick here, but could you maybe change the commit message to contain `packer.nvim` instead of `Packer` ?~~

Nevermind. Went ahead and did that for 'ya :blush:

**Review by andersevenrud — COMMENTED** [review]
GH would not allow me to finish my review... so this is just a test.

*Edit* I have no idea what's going on here. The UI broke on me. But consider this approved :joy:

**Comment by gegoune** [comment]
Thank you! Sorry, read your comment too late, wouldn't mind changing commit message, of course.

**Comment by andersevenrud** [comment]
No worries! I just figured I'd do it myself because it was such a minor thing :sweat_smile:

**Pull request merged**
