### PR TITLE
Various cleanups and improvements

### PR DESCRIPTION
**Pull request by andersevenrud**
I noticed that I forgot to remove a statement from my last PR... https://github.com/maaslalani/nordbuddy/commit/ac4e971e366ff891585efee770ea2266a88003ab#diff-36c51489421ce700b3ab015e5b787c2eb6497cfebb6a80f66d44741ee9f69756R110-R112

...and I thought I'd just go all out since I started a small cleanup.

This replaces some conditions with a ternary (or "fakeary" as i call them :joy:) and removes some dead code.

Also, since things shrunk quite a bit afterwards, I decided to weld together these create functions together into one basically named `create_arguments`, because that was basically all we were doing.

### CODE REVIEW

**Review by maaslalani — APPROVED** [review]
Thanks for all this cleanup!

**Comment by andersevenrud** [comment]
Ain't no thing @maaslalani !

I was contemplating shortening down the terminal coloring section to the following:

```lua
    local term_colors = { 1, 11, 14, 13, 9, 15, 8, 5, 3, 11, 14, 13, 9, 15, 7, 6 }
    for k, v in ipairs(term_colors) do
        vim.g['terminal_color_' .. tostring(k - 1)] = v
    end
```

... not really sure though, because it might become a bit fiddly to change this ?! What do you guys think ?

**Comment by maaslalani** [comment]
I think its okay to leave it as is. I'd prefer readability/maintainability over code density. But its probably won't change much so up to you.

**Comment by andersevenrud** [comment]
> I'd prefer readability/maintainability over code density.

My thoughts exactly. I'll leave it as is then :nerd_face:

**Comment by andersevenrud** [comment]
@maaslalani I made another commit here that significantly cuts down on the amount of code here, so I need a new review :blush: 

Basically since colorbuddy is out of the picture,  and considering the discussion we had while doing the perf stuff, I decided to ditch the `c`, `s`, etc. remnants entirely, and you now have to give string literals.

In the case of the "custom styles" (i.e. user settings), these have now simply been prefixed with `user_`, so `italic` would be standard style and `user_italic` is the one that is toggleable by the user. So I've refactored the color modules to do this instead.

This had a knock-on effect which lead to dramatic reduction of bootstrap code with a few tricks that I learned (Lua is still relatively new to me... but you can chain `or`-s..that's awesome!).

**Comment by maaslalani** [comment]
Instead of strings directly can we name them the colours, e.g. `c.red`, `c.yellow`, `c.magenta`?

I think that will make it a lot nicer to read and edit the colorscheme. Since right now I have to have the palette open in a split while editing so I think labeling them will be super useful. Personally not a huge fan of the strings since its much easier to make typos and you don't get editor/linting errors.

**Review by maaslalani — CHANGES_REQUESTED** [review]
I'm not for the literal strings since you can make typos and don't get any errors, we should make a table and have the labelled colours like suggested above ^

**Comment by andersevenrud** [comment]
> Since right now I have to have the palette open in a split while editing so I think labeling them will be super useful.

I thought about this, but since in this case the palette is pretty much fixed I thought maybe this was not really an issue.

> I'm not for the literal strings since you can make typos and don't get any errors

The thing is, you would not get any error feedback outside LSP, ~~but actually, since there is no docblocks you would not be able to see these completion options~~ ops, it actually does, but for some reason my server keeps crashing. Gotta say I miss strict typing a bit :D

> we should make a table and have the labelled colours like suggested above 

This would also apply to styles then ? So you'd have `c` and `s` as it were (though no `cs` because this was merged into `s` which I think is nice).

Also, actual names we can do -- but that's best fit in another PR.

**Comment by andersevenrud** [comment]
> The thing is, you would not get any error feedback outside LSP

Runtime errors can be easily added for this though, but you're probably thinking more on the editor side of things.

**Comment by maaslalani** [comment]
> you would not get any error feedback outside LSP

Yes, I would like the feedback inside the LSP though.

**Comment by maaslalani** [comment]
Happy to do the labelling in another PR, but lets revert the literal strings commit

**Comment by andersevenrud** [comment]
Mkay. It's been reverted :sweat_smile:

**Review by maaslalani — APPROVED** [review]

**Comment by andersevenrud** [comment]
I reconsidered and smashed the color names into this one as well.

**Comment by andersevenrud** [comment]
NB: The "light" variants of the previous `nord<n>` ones are now called `<color>ish` because I became a bit stumped as to how to name them. These were previously from the lighten methods of colorbuddy, and there's just two of them.

**Review by maaslalani — APPROVED** [review]
Looks great

**Comment by andersevenrud** [comment]
Alrighty then. Thanks for the feedback!

As of this PR my itch finally has been scratched when it comes improving things that's been on my mind for a while. Sorry for all the inbox noise :blush:

**Pull request merged**
