### PR TITLE
feat: hl groups for 'glepnir/dashboard-nvim'

### PR DESCRIPTION
**Pull request by delafthi**

### CODE REVIEW

**Comment by andersevenrud** [comment]
You need to add the file to `lua/nordic/colors/init.lua`.

**Comment by delafthi** [comment]
> You need to add the file to `lua/nordic/colors/init.lua`.

Of course, thank you for the hint.

**Comment by andersevenrud** [comment]
Could you share a screenshot of how this looks ? :blush:

**Comment by delafthi** [comment]
Sure,
dashboard


The plugin seen in this screenshot is not dashboard-nvim. I use [alpha-nvim](https://github.com/goolord/alpha-nvim), which does not define custom hl groups. However, I assigned the hl groups of dashboard to the according elements of the alpha dashboard. Thus it should look similar. Additionally, I quickly added a random footer, because in my config I use none.

**Comment by andersevenrud** [comment]
I tried to resolve the conflict myself with the Github functionality... well, that didn't work :joy: 

It's stuck on:

> This branch cannot be rebased due to conflicts

I think you have to do a force-push here, because I can't select rebase, squash or anything.

**Comment by delafthi** [comment]
I rebased on upstream/main. Let's hope it works this time :pray:.

**Comment by andersevenrud** [comment]
Why was this closed ? :)

**Comment by delafthi** [comment]
> Why was this closed ? :)

I deleted my feature branch to early (and did not read the warning message) which closed the PR without merge. After recognizing what happened, I reverted the restored the deleted branch and reopened the PR. Sry again for the hassle 🙄. I'm not that used to contributing. But I learn something new with every mistake I make 💁‍♂️.

**Comment by delafthi** [comment]
Oh, I see... :man_facepalming:. I hope I'm able this time :laughing:.

**Pull request merged**
