### PR TITLE
feat: add underdash, underdot and underlineline styles

### LINKED ISSUE #74: Add support for double, dashed, and dotted underlines
Another nvim improvement that can be leveraged by nordic.nvim: https://github.com/neovim/neovim/pull/17589 (for supporting terminal emulators).

Can you think of any feasible applications?

### PR DESCRIPTION
**Pull request by gegoune**
This PR adds support for three new highlight styles:
https://github.com/neovim/neovim/pull/17589

Closes #74

### CODE REVIEW

**Review by andersevenrud — APPROVED** [review]

**Comment by andersevenrud** [comment]
Thanks!

**Comment by gegoune** [comment]
Thank you! Can you think of some sensible applications?

**Comment by andersevenrud** [comment]
Diagnostics and spelling comes to mind. I don't have a terminal with support, so I'm not really sure how that'd look like :sweat_smile:

**Comment by gegoune** [comment]
[Wezterm](https://wezfurlong.org/wezterm/) supports them all if you want to have a look. I will see if I can find anything that looks good.

**Pull request merged**
