### PR TITLE
Add `CopilotSuggestion` to colorscheme

### PR DESCRIPTION
**Pull request by maaslalani**
Adds `CopilotSuggestion` to `c.gray` instead of `#808080`

### CODE REVIEW

**Review by andersevenrud — CHANGES_REQUESTED** [review]
Could you maybe change the commit message to `Add support for copilot.vim` so that it's consistent with the history ? :blush:

**Comment by maaslalani** [comment]
Done!

**Review by andersevenrud — APPROVED** [review]
Thanks! :bow:

**Comment by maaslalani** [comment]
> Could you maybe change the commit message to `Add support for copilot.vim` so that it's consistent with the history ? 😊

@andersevenrud You should add this to the `CONTRIBUTING.md` if possible (unless its already written somewhere and I completely missed it)

**Comment by andersevenrud** [comment]
I will :smile:  Thanks for the tip!

**Pull request merged**
