### PR TITLE
feat: hl groups for 'p00f/nvim-ts-rainbow'

### PR DESCRIPTION
**Pull request by delafthi**

### CODE REVIEW

**Comment by andersevenrud** [comment]
You need to add the file to `lua/nordic/colors/init.lua`.

**Comment by delafthi** [comment]
> You need to add the file to `lua/nordic/colors/init.lua`.

Of course, thank you for the hint.

**Comment by andersevenrud** [comment]
Could you share a screenshot of how this looks ? :blush:

**Comment by delafthi** [comment]
Sure,
rainbow

**Comment by andersevenrud** [comment]
LGTM. Thanks!

**Pull request merged**
