### PR TITLE
feat: add GitSignsDeleteLn highlight group

### PR DESCRIPTION
**Pull request by gegoune**
It's screams right in your face now, not sure which combination of palette could look good.

It's GitSigns' newly added feature (https://github.com/lewis6991/gitsigns.nvim/pull/443).

### CODE REVIEW

**Comment by andersevenrud** [comment]
I'm not at my workstation. Would you mind attaching a screenshot here ?

**Comment by gegoune** [comment]
Sure, here it is:
gs
Could probably do with less 'in your face' background.

**Comment by andersevenrud** [comment]
Maybe simply stepping down to `dark_white` as the `guifg` makes it a bit less aggressive ?

Alternatively, you could try using `bright_black` as the `guibg` and then use the red/green as `guifg` to make it less 'in the face'.

The latter is how I'm used to it being in neogit, so might be a bit biased, heh.

**Comment by andersevenrud** [comment]
Personally, I think that it looks OK. At least if it's something that is toggled to get an overview... not sure how it would be if it was there permanently :sweat_smile:

**Comment by gegoune** [comment]
> Maybe simply stepping down to `dark_white` as the `guifg` makes it a bit less aggressive ?
Screenshot 2022-01-14 at 21 29 33


> Alternatively, you could try using `bright_black` as the `guibg` and then use the red/green as `guifg` to make it less 'in the face'.
Screenshot 2022-01-14 at 21 29 00

**Comment by andersevenrud** [comment]
And with `red` on the `guifg` on that last one ?

**Comment by gegoune** [comment]
Screenshot 2022-01-14 at 21 34 27
Might be the best one so far. 🤷‍♂️

**Review by andersevenrud — APPROVED** [review]
Looks good to me! Actually, both do (the red bg or the red fg).

However, I'm leaning towards the last draft (gray bg, red fg).

I'll let you decide here :smile:

**Review by andersevenrud — COMMENTED** [review]
There's a typo in your commit message btw (`highkight`) :)

**Comment by gegoune** [comment]
Fixed. Don't feel like am in position to make decision. You tell me. :)

**Comment by andersevenrud** [comment]
> Fixed

I was thinking of the commit, not the pull request :smile: 

> You tell me. :)

If you don't have a preference, then let's go for the white foreground one.

**Comment by gegoune** [comment]
White on red background or bright_black background? (Will fix commit by force pushing with new changes)

**Comment by andersevenrud** [comment]
> bright_black background

This one with the red text. Just as in the last screenshot.

**Comment by gegoune** [comment]
OK, should be all good now.

**Comment by andersevenrud** [comment]
Thanks!

**Comment by gegoune** [comment]
Thank you!

**Pull request merged**
