### PR TITLE
fix: Update to use treesitter queries instead of obsolete TS* highlight groups.

### PR DESCRIPTION
**Pull request by dsully**
See: https://github.com/nvim-treesitter/nvim-treesitter/pull/3656

### CODE REVIEW

**Comment by andersevenrud** [comment]
Looking at the referenced pull-request:

> BREAKING CHANGE: assign highlights to captures directly (e.g., hi link @keyword Keyword).
> Drops support for Nvim 0.7

Since this won't roll out to everyone immediately, I think it might be best to keep the "old" highlight groups and add some annotations with comments in the code to remove this down the line when it's "safe".

**Comment by dsully** [comment]
I believe this change will work for everyone, as the `@` style queries have always been able to be used by nvim-treesitter.

**Comment by andersevenrud** [comment]
> I believe this change will work for everyone

It's pretty late here, and gotta hit the bed, so I can't look this up myself. But if you could drop a link to a resource confirming this, it would be much appreciated. Haven't really kept up with developments on the tresitter-side of things recently either :sweat_smile:

**Comment by dsully** [comment]
More here: https://www.reddit.com/r/neovim/comments/y5rofg/recent_treesitter_update_borked_highlighting/

**Comment by andersevenrud** [comment]
Yeah... I still think that having the old definitions would be a good idea here. I have some of my plugins version pinned etc. and I imagine others might as well, so removing these might cause accidental breakage for some.

**Comment by dsully** [comment]
> Yeah... I still think that having the old definitions would be a good idea here. I have some of my plugins version pinned etc. and I imagine others might as well, so removing these might cause accidental breakage for some.

Let me rework this to have both, since that should be forward & backwards compatible. Sound good?

**Comment by andersevenrud** [comment]
> Sound good?

Yup :)

**Comment by andersevenrud** [comment]
Btw, don't worry about the commit message lint. We can squash this PR when done and add the correct format then.

**Comment by andersevenrud** [comment]
Thanks!

**Pull request merged**
