### PR TITLE
Minimal tabs

### PR DESCRIPTION
**Pull request by maaslalani**
Really minimal tabline.

I'm guessing most people use Barbar or Bufferline and those who don't (me!) might like a much more minimal look?

Opinions welcome

### CODE REVIEW

**Comment by maaslalani** [comment]
image

**Comment by maaslalani** [comment]
Another option
image

**Comment by f3fora** [comment]
Can you pass an extra parameter? Eg.`require('nordbuddy'):colorscheme({minimal_tabs = true})`. 
Moreover, should we update the picture in README?

**Comment by andersevenrud** [comment]
> I'm guessing most people use Barbar or Bufferline and those who don't (me!) might like a much more minimal look?

I'm on team not using those. I tried it out, bur it was more of an annoyance than anything else :D

**Comment by andersevenrud** [comment]
As mentioned in #31; this kind of messes up the visibility of the tab bar. I would love to have an option to have it in "minimal mode" or "standard", where the latter has a different background color and the former sort of a "zen" thing for anyone that's into that.

**Comment by maaslalani** [comment]
Yea I like the idea of "minimal"/"zen" mode

**Comment by maaslalani** [comment]
Need to add this with behind a "minimal" mode toggle

**Pull request closed without merging**
